//This file was auto generated by quickbase_updater tool named: quick_base_config.js
//This file can be found at git repo: git@git.emerge-technology.com:jolpatx/quickbase_updater.git

// ENVIRONMENT SWITCH
// DB designation switching for multiple environment scenarios
// - Replace the string in var ENVO_switch.state:_____ to select an environment.

var ENVO_switch = {state: "dev_on_core_content"};

switch (ENVO_switch.state) {
    case 'production':
        ENVO_switch = {
            state: 'on_production',
            vams: 'bjehsrvjq',
            galleryItems: 'bjehsrvkc',
            galleryAssets: 'bjehsrvkd',
            projectLocales: 'bjehsrvki'
        };
    break;

    case 'dev_on_core_content':
        ENVO_switch = {
            state: 'on_Core_Content_Dev',
            vams: 'bkpb7tekb',
            galleryItems: 'bkpb7teur',
            galleryAssets: 'bkpb7tezx',
            projectLocales: 'bkpb7tfr4',

            change: [
                {'new_vams.floatingCoreContent': '201442'}
            ]
        };
    break;

    default:
    // 'state' should be on 'production' if LIVE
}

/// Configuration used by RUMI run time
var db_config =
{
    quickbase:{
        server : 'https://radius60.quickbase.com',
        username: 'jolpat@radius60.com',
        password: 'gcwqs8b45eb8',
        apptoken: 'dneqmhjbiabn9kdjsivzmfzd6qt',
        dbid: 'bjehsrvaj',  // RUMI
        rid:'3'
    },
    
    // DUMMY APPs to test with
    appTesting: {
        // Digital Delivery Scheduling TEST
        DDscheduling: {
            DBBorders_dbid:     'bjwdcmwmr'
        },
        // Sony Hub Integration TEST
        SHintegration: {
            dbid:               'bkejayxsb',
            delTasks_dbid:      'bkejayxsj'
        }
    },

    tasksApp: {
        apptoken: 'b35vc8nd5rbwq2bhtt7zcd6anz8j',
        tasksTable: {
            dbid: 'bjr24caej'
        }
    },
    
    titles:
    {
         dbid: "bhujxtum5"
    },
    marketingDesc:
    {
         dbid: "bi53wunyw",
         titleFid: '8',
         descFid:'6'
         
    },
 
      
    providers:
    {
        dbid: "birsebby9",
        providerNameFID: '16',
        
    },
    extras: //DD Table
    {
        dbid: "biu56td2a",
        vamFid: '59',
        tableTitleFid: '6',
        titleFid: '7',
        vendoridFid: '10',
        territoriesFid: '86',
        clientFid : '8',
        langFid: '108',
        project_rid: '9',
        providerFid: '167',
        streetDateFid: '13',
        current_statusFid: '41',
        project_titleFid: '63',
        title_alpha_idFid: '97',
        project_priority_Fid: '159'
    },
    extrasTickets: // Extras Issue Tickets
    {
        dbid:'biz6hancg'
    },
    projects://// title alpha -> extras delivery ALex table
    {
        dbid: "bhujycjtk",
        vendoridFid: '6',
        title_alphaFid:'15'
    },
    filmVersions:
    {
        dbid: "bhujy3yxh",
        titleFid: "6",
        relatedAlphaFid: "8",
        contentTypeFid: "97",
        vamNameFid: "104",
        ridFid: '3'
    },
    encodeJobs:
    {
        dbid: "bhxm2t7cv",
        relatedTitleFid: "6",
        relatedTitleAlphaFid: "8"
    },
    conditionalDropDowns:
    {
        dbid: "bhujxyyyr",
        matchConditionFid: "9",
        resultConditionFid: "6"
    },
    assetsMaster:
    {
        dbid: "bjzsbhtvm",
        vamNameFid: "7",
        clientFid: "10",
        typeFid: "6",
        relatedTitleFid: "9"
    },
    scene_group:
    {
        dbid: "bjehsrvj6",
        gidFid: '6',
        title_alphaFid:'28',
        orderFid:'24',
        titleFid:'25'
    },
    scenes:
    {
        dbid: "bjehsrvj7",
        intimeFid: '6',
        outtimeFid:'7',
        imageFid:'8',
        groupidFid:'23',
        title_alphaFid:'34',
        orderFid:'28',
        key_sceneFid:'29'
    },
    authoring:
    {
        dbid: "bjehsrvjt",
        territory_menuFid: "22",
        flagFid: "7",
        language: "28",
        provider: "29",
        extras_deliver_rid: "57",
        inFolderFid: "6",
        content_idFid: "68",
        vendor_id_prefixFid: "44",
        timecode_formatFid: '71',
        releaseDateFid: '72',
        verificationRIDFid:'73',
        deliveryRIDFid:'74',
        package_versionFid: '75',
        specs_versionFid: '76',
        include_in_del_Fid:'77',
        scenes_offsetFid:'78',
        scenes_multiplierFid: '79',
        project_source_nameFid: '89'

        
    
    },
    package_languages: //// 
    {
        dbid: "bjq44jks9",
        packageFid: "9",
        languageFid: "7",
        typeFid: "8"
 
    
    },
    //
    territory_menu: //root menu item
    {
        dbid: "bjehsrvju",
        menuFid: "24", //rid in menu items table
        titleFid: "20",
        vendor_idFid:   "7",
        extrasFid: "30",
        orderFid: "6",
        include_in_del_Fid:'32'
    },
    territory_menu_list:
    {
        dbid: "bjehsrvj2",
        menu_ridFid: "7",
        typeFid: '12',
        valueFid: '11'
        
    },
    menu_items:
    {
        dbid: "bjehsrvj5",
        typeFid: '6',
        orderFid: '18',
        templateFid: '9',
        parentFid: '32',
        play_allFid: '31',
        inherit_audioFid: '59',
        inherit_imageFid: '60',
        package_ridFid: '68',
        MarkDelivery_Fid: '69',
        masterFid: '74',
        parent_titleFid: '73',
        background_colorFID :'76',
        title_colorFID          :'77',
        primary_text_colorFID   :'78',  
        remove_from_deliveryFID :'79' ,
        transitionFID: '80'
        
    },
    locale:
    {
        dbid: ENVO_switch.projectLocales,//"bjehsrvki",
        titleFid: '39',
        descFid: '43',
        tagFid: '9',
        valueFid: '8',
        langFid: '7',
        sidFid: '6',
        parent_rid: '18',
        cc_flag: 'asdf'
    },
    studioLocales:
    {
        dbid: "bjehsrvke",
        localeFid: "6",
        valueFid: "7",
        clientFid: "9",
        stringFid: "10",
        defaultFid: "15"
    },
    gallery:
    {
        dbid: "bjehsrvj9",
        package_rid: "35",
        typeFid: "7",
        idFid:"6",
        stateFid: '13',
        masterFid: '37',
        parent_titleFid: '36',
        inherit_titleFID: '38',
        durationFID: '39',
        loop_countFID: '40',
        galleryAutonameFID:'41',
        include_in_del_Fid:'43',
        relatedAssetMasterFid: '44'
    },
    advanced: //Add table
    {
         dbid: "bjehsrvks",
         sidFid: "6",
         package_rid: "7",
         categoryFid: "9",
         tagFid: "10",
         valueFid: "11"
    },
    vams:
    {
        dbid: ENVO_switch.vams,//"bjehsrvjq",
        tableTitleFid: '6',
        typeFid: '16',
        categoryFid: '8',
        relatedFid: '10',
        notesFid: '29',
        descFid: '7'
    },
    new_vams:
    {
        dbid: ENVO_switch.vams,//"bjehsrvjq",
        rid: '3',
        titleFid: '37',
        categoryFid: '6',
        assetFid: '7',
        thumbnailFid: '13',
        narrativeLocaleFid: '14',
        subtitleLocaleFid: '42',
        audioLocaleFid: '43',
        textlessmasterFid: '8',
        croptopFid: '9',
        cropbottomFid: '10',
        croprightFid: '11',
        cropleftFid: '12',
        daterecievedFid: '30',
        missingFid: '28',
        exclusiveVamMatchFid: '29',
        relatedFilmVersionFid :'44',
        durationFid: '45',
        floatingCoreContent: '46' // '48' on DEV
    },
    gallery_item:
    {
        dbid: ENVO_switch.galleryItems,//"bjehsrvkc", //<--Production 
        typeFid: '6',
        gallery_idFid: '10', //gallery vendor id 
        orderFid: '12',
        vendor_idFid: '7',
        legacy_videoFid: '21',
        useLegacy_videoFid: '25',
        gallery_ridFid: '9',
        package_ridFid: '22',
        masterFid: '24',
        parent_titleFid: '23',
        linkedFid: '29',
        commentaryFid: '30'
    },
    gallery_asset:
    {
        dbid: ENVO_switch.galleryAssets,//"bjehsrvkd", //<--Production
        typeFid: '12',
        gallery_idFid: '13',
        orderFid: '6',
        filenameFid: '7',
        propFid: '8',
        vamFid: '10', //for video files
        old_vamFid: '16',
        package_ridFid: '18',
        sizeFid: '21',
        md5Fid: '22',
        include_in_del_Fid: '20',
        localeFid: '19',
        parent_titleFid: '23',
        parent_gallery: '24',
        floatCCFlagFid: '25'
    },
    remove_from_delivery_list:
    {
        dbid: "bjsyff6vc",
        project_idFid: '6',
        vendor_idFid: '7',
        typeFid: '8'
    },
    archive:
    {
        dbid: "bjv7kyx8b",
        extras_idFID: "6",
        release_dateFID: "7",
        content_idFID: "8",
        providerFID: "9",
        archiveFID: "10",
        arch_dateFID: "11",
        labelFID: "12",
    },
    testingTarget:
    {
        itemID: "32766", // "58957",//
        assetID: "122469",
        vamID: "7161"
    }
};


// Applies field ID propery changes 
// for each requested single pair object 
// included in the 'ENVO_switch.change' property.

// Requests should be an array of single pair objects with 
// key being the property path and
// value being the new value
var ENVO_switchPropertyChanges = function(requests) {
    if (!requests) {
        console.log('There were no db_config value change reqeusts!');
    }else{
        var listOfChanges = requests;
        console.log('ENVO_switch will do these changes on the db_config', listOfChanges);

        listOfChanges.forEach(function(changeReq, index, list){
            var propertyPathStr = Object.keys(changeReq)[0];
            var propertyPath = propertyPathStr.split('.');
            console.log(
                'ENVO_switch will change:', propertyPathStr,
                '\nto:', changeReq[propertyPathStr]
            );

            switch (propertyPath.length) {
                case 2:
                    db_config[propertyPath[0]][propertyPath[1]] = changeReq[propertyPathStr];
                break;
                default:
                // needs a case!
            }
        });
    }
}; //END ENVO_switchPropertyChanges
ENVO_switchPropertyChanges(ENVO_switch.change);

